name: Docker Image CI

on:
  push
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Get the docker file
          run: |
            git clone https://github.com/threeML/docker_base.git
            cd docker_base
          
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Get the version
          uses: actions-ecosystem/action-get-latest-tag@v1
          id: vars

        - name: Build the tagged Docker image for ${{steps.vars.outputs.tag}}
          run: docker build . --file Dockerfile --tag threeml/base:${{steps.vars.outputs.tag}}
        # - name: Push the tagged Docker image
        #   run: docker push threeml/base:${{steps.vars.outputs.tag}}
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag threeml/base:latest
        # - name: Push the latest Docker image
        #   run: docker push pjlamb12/angular-cli:latest
